tap "homebrew/bundle"
tap "homebrew/cask-versions"
brew "diff-so-fancy"
brew "fzf"
brew "gh"
brew "git"
brew "gnupg"
brew "htop"
brew "jq"
brew "libpq"
brew "pnpm"
brew "vim"
brew "watch"
cask "insomnia"
cask "visual-studio-code"
cask "docker"

# fzf.vim deps
brew "bat"
brew "perl"
brew "ripgrep"
brew "the_silver_searcher"
brew "universal-ctags"
