# git
alias ga='git add -A'
alias gb='git branch'
alias gco='git checkout'
alias gc='git commit'
alias gd='git diff'
alias gds='git diff --staged'
alias gp='git pull'
alias gpu='git push'
alias gs='git status'
