# git
alias ga='git add -A'
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch --prune'
alias gp='git pull --prune'
alias gpu='git push'
alias gs='git status'
